version: 2.1

executors:
  cpp:
    docker:
      - image: circleci/cpp:latest

jobs:
  build:
    executor: cpp     # set executor to use CircleCI's pre-installed C++ environment
    steps:
      - checkout
      - run:
          name: Build and Zip Project
          command: |
            mkdir build
            cd build
            cmake ..
            make
            zip -r project.zip *
            cp project.zip $CIRCLE_ARTIFACTS
    working_directory: ~/repo
