version: 2.1

jobs:
  build:
    docker:
      - image: circleci/cpp:latest
    working_directory: /tmp
    steps:
      - checkout

      # Install vcpkg dependencies
      - run:
          name: Install vcpkg dependencies
          command: |
            git clone https://github.com/Microsoft/vcpkg.git /tmp/vcpkg
            /tmp/vcpkg/bootstrap-vcpkg.sh
            /tmp/vcpkg/vcpkg install protobuf:x64-linux

      # Build the project
      - run:
          name: Build
          command: |
            mkdir build
            cd build
            cmake ..
            make

      # Create a binary artifact
      - run:
          name: Create a zip file
          command: |
            mkdir -p artifacts
            zip -r artifacts/binary-artifact.zip /tmp/build/your-project-name

      - store_artifacts:
          path: artifacts/binary-artifact.zip
          destination: binary-artifact.zip

workflows:
  build-and-package:
    jobs:
      - build
