version: 2.1

jobs:
  build:
    docker:
      - image: circleci/cpp:latest
    environment:
      VCPKG_DEFAULT_TRIPLET: x64-linux
    steps:
      - checkout
      - run: |
          sudo apt-get update
          sudo apt-get install -y cmake
          git clone https://github.com/Microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
      - run:
          name: Install dependencies
          command: |
            ./vcpkg/vcpkg install protobuf
      - run:
          name: Build project
          command: |
            mkdir build
            cd build
            cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
            make
      - run:
          name: Package artifacts
          command: |
            mkdir artifacts
            zip artifacts/output.zip build/*

      - store_artifacts:
          path: artifacts/output.zip

workflows:
  version: 2
  build:
    jobs:
      - build
