version: 2.1

jobs:
  build:
    working_directory: /tmp/project
    parallelism: 1
    shell: /bin/bash --login

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y build-essential
            sudo apt-get install -y libprotobuf-dev protobuf-compiler
            sudo apt-get install -y cmake

      - run:
          name: Build project
          command: |
            mkdir build
            cd build
            cmake ..
            make
            zip -r ../project.zip *

      - store_artifacts:
          path: /tmp/project/project.zip
          destination: project.zip

workflows:
  build:
    jobs:
      - build
